front_homepage:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

stages:
    path:     /stages
    defaults: { _controller: FrontBundle:Default:stages }


galerie:
    path:     /galerie
    defaults: { _controller: FrontBundle:Default:galerie }

stage:
    path:     /stage/{id}
    defaults: { _controller: FrontBundle:Default:stage }

postuler:
    path:     /postuler/{id}
    defaults: { _controller: FrontBundle:Default:postuler }
