admin_stage:
    resource: "@AdminBundle/Resources/config/routing/stage.yml"
    prefix:   /admin/stage

admin_homepage:
    path:     /admin
    defaults: { _controller: AdminBundle:Default:index }

merci:
    path:     /send/success
    defaults: { _controller: AdminBundle:merci:index }
