stage_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Stage:edit" }
stage_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Stage:delete" }
liste_stages:
    path:     /admin/liste_stages
    defaults: { _controller: AdminBundle:Default:listeStages }
ajout_stage:
    path:     /admin/ajout_stage
    defaults: { _controller: AdminBundle:Default:ajoutStage }
